"use client"

import React, { useState } from 'react'
import axios from 'axios'
import { showToast } from '@/utils'
import { X, ClipboardList } from 'lucide-react'
import { UserData } from '@/interfaces';
import { Button } from '@/components/ui/button'

interface AddTaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSaved: () => void;
  users: UserData[];
  projectId: string;
  projectCode?: string;
  projectDepartment?: string;
}


export function AddTaskModal({
  isOpen,
  onClose,
  onSaved,
  users,
  projectId,
  projectCode,
  projectDepartment
}: AddTaskModalProps) {
  const [formData, setFormData] = useState({
    id: '',
    task_name: '',
    description: '',
    assignee_id: [] as string[],
    start_date: '',
    due_date: '',

    status: 'To Do',
    priority: 'Medium'
  })

  const [isSubmitting, setIsSubmitting] = useState(false)

  React.useEffect(() => {
    if (isOpen) {
      const tid = setTimeout(() => {
        setFormData(prev => ({ ...prev, id: `TSK-${Math.floor(Math.random() * 10000)}` }));
      }, 0);
      return () => clearTimeout(tid);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!formData.task_name) {
      showToast.error("Missing fields", "Task Name is required.")
      return
    }

    try {
      setIsSubmitting(true)

      const res = await axios.post('/api/tasks', {
        ...formData,
        project_id: projectId
      })

      if (res.data.status === 'success') {
        showToast.success("Task Created", "New task has been added to the project.")
        // Reset form
        setFormData({
          id: '',
          task_name: '',
          description: '',
          assignee_id: [] as string[],
          start_date: '',
          due_date: '',
          status: 'To Do',
          priority: 'Medium'
        })
        onSaved()
        onClose()
      } else {
        throw new Error(res.data.message)
      }
    } catch (error: unknown) {
      const err = error as { response?: { data?: { message?: string } }; message?: string };
      console.error("Failed to save task:", err)
      showToast.error("Error", err.response?.data?.message || err.message || "Failed to create task")
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-2xl max-h-[90vh] flex flex-col animate-in zoom-in-95 duration-200">

        {/* Header */}
        <div className="flex items-center justify-between px-3 py-2 border-b border-slate-100 bg-slate-50/50">
          <h3 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
            <ClipboardList className="w-5 h-5 text-indigo-600" />
            Add New Task
          </h3>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 transition-colors p-1 rounded-full hover:bg-slate-100"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-6 overflow-y-auto flex-1 space-y-5">

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Task ID</label>
              <input
                name="id"
                type="text"
                disabled
                value="Auto-generated by system"
                className="w-full px-3 py-2 border border-slate-200 rounded-lg bg-slate-100 text-slate-500 cursor-not-allowed"
              />
              <p className="text-xs text-slate-500 mt-1">Format: TSK-{projectCode || 'PROJECT'}-XXX</p>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Task Name <span className="text-red-500">*</span></label>
              <input
                name="task_name"
                type="text"
                required
                value={formData.task_name}
                onChange={handleChange}
                placeholder="e.g. Design Homepage"
                className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors"
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Description</label>
            <textarea
              name="description"
              rows={3}
              value={formData.description}
              onChange={handleChange}
              placeholder="Detailed description of the task..."
              className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors resize-none"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Assignees (@mention)</label>
            <div className="w-full px-3 py-2 border border-slate-200 rounded-lg bg-white max-h-40 overflow-y-auto space-y-2">
              {users.filter(u => {
                if (!projectDepartment) return true;
                const allowedDepts = projectDepartment.split(',').map(d => d.trim().toLowerCase());
                return allowedDepts.includes((u.department || "").toLowerCase());
              }).map(user => {
                const uid = user.id || "";
                return (
                  <label key={uid} className="flex items-center space-x-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={formData.assignee_id.includes(uid)}
                      onChange={(e) => {
                        const checked = e.target.checked;
                        setFormData(prev => ({
                          ...prev,
                          assignee_id: checked 
                            ? [...prev.assignee_id, uid] 
                            : prev.assignee_id.filter(id => id !== uid)
                        }));
                      }}
                      className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                    />
                    <span className="text-sm text-slate-700">
                      {user.name_th || user.name_en} <span className="text-slate-400 text-xs">({user.department || user.position})</span>
                    </span>
                  </label>
                );
              })}
              {users.filter(u => {
                if (!projectDepartment) return true;
                const allowedDepts = projectDepartment.split(',').map(d => d.trim().toLowerCase());
                return allowedDepts.includes((u.department || "").toLowerCase());
              }).length === 0 && (
                <div className="text-sm text-slate-400 italic py-1">No users found in project departments</div>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Start Date</label>
              <input
                name="start_date"
                type="date"
                value={formData.start_date}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Due Date</label>
              <input
                name="due_date"
                type="date"
                value={formData.due_date}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Status</label>
              <select
                name="status"
                value={formData.status}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors bg-white"
              >
                <option value="To Do">To Do</option>
                <option value="In Progress">In Progress</option>
                <option value="Review">Review</option>
                <option value="Done">Done</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Priority</label>
              <select
                name="priority"
                value={formData.priority}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors bg-white"
              >
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
              </select>
            </div>
          </div>

          {/* Actions */}
          <div className="pt-4 flex justify-end gap-3 border-t border-slate-100 mt-6">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={isSubmitting} className="bg-indigo-600 hover:bg-indigo-700 text-white">
              {isSubmitting ? "Saving..." : "Save Task"}
            </Button>
          </div>
        </form>

      </div>
    </div>
  )
}
